### ISSUE TITLE
[Help] Use Zebra_cURL with cloudflare-bypass

### ISSUE THREAD

**Issue by Dibbyo456** [stefangabos/Zebra_cURL#27]
I know, this is not exactly an issue, but is there anyway I can use the [cloudflare-bypass](https://github.com/KyranRana/cloudflare-bypass/blob/master/v2/examples/curl.php) with zebra_curl?

I just wanna perform simple get request without callback (scrape)

**Comment by stefangabos** [comment]
Zebra_cURL does have [a method for scrapping](https://stefangabos.github.io/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodscrap) but by-passing Cloud Flare's protection is much more than that...

**Comment by Dibbyo456** [comment]
That is exactly what I'm using with my script.
But unfortunately I also needs to bypass the the cloudflare ddos protection. The link I mentioned works just fine. But I was wondering if it's possible to just use their codes in zebra url.
Otherwise I would have to ditch zebra curl and rewrite curl codes from scratch because bypassing cf is no. 1 priority.

**Comment by stefangabos** [comment]
I can't help you with that. This library does what it says on the box :) 
_that code_ uses a lot of other code in order to bypass CloudFlare's protection, and the `cURL` parts is just a small part of it. You don't need to rewrite the cURL codes but more like you need to implement CloudFlare bypassing with Zebra_cURL"...
