### ISSUE TITLE
Setting max load while executing a lot of get requests

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [stefangabos/Zebra_cURL#47]
Hi

I have a question. I want to use this library to send a lot of get request to a website, for cache warming. But I want to monitor the system load by sys_getloadavg, so I will not be higher then 10%. 

When can I add this in the code, _process()?

Best regards
Dennis

**Comment by stefangabos** [comment]
Maybe using [this](https://github.com/stefangabos/Zebra_cURL/issues/34#issuecomment-489538919) as a starting point. Basically, I would send x number of requests at once and check `sys_getloadavg` as each one ends. Based upon the result I would either keep sending x number of requests or i would increase/decrease the number of requests per batch in order to stay withing my threshold.
